/*	Red's team from GSC
	Source: https://bulbapedia.bulbagarden.net/wiki/Red_(game)#Pok.C3.A9mon_Gold.2C_Silver.2C_and_Crystal	*/
export const red = [
	{
		name: "Pikachu",
		dexNo: 25,
		level: 81,
		gender: "male",
		type1: "Electric",
		type2: "",
		moves: ["Charm", "Quick Attack", "Thunderbolt", "Thunder"],
	},
	{
		name: "Espeon",
		dexNo: 196,
		level: 73,
		gender: "male",
		type1: "Psychic",
		type2: "",
		moves: ["Mud Slap", "Swift", "Reflect", "Psychic"],
	},
	{
		name: "Snorlax",
		dexNo: 143,
		level: 75,
		gender: "male",
		type1: "Normal",
		type2: null,
		moves: ["Amnesia", "Snore", "Rest", "Body Slam"],
	},
	{
		name: "Venusaur",
		dexNo: 3,
		level: 77,
		gender: "male",
		type1: "Grass",
		type2: "Poison",
		moves: ["Sunny Day", "Giga Drain", "Synthesis", "SolarBeam"],
	},
	{
		name: "Charizard",
		dexNo: 6,
		level: 77,
		gender: "male",
		type1: "Fire",
		type2: "Flying",
		moves: ["Flamethrower", "Wing Attack", "Slash", "Fire Spin"],
	},
	{
		name: "Blastoise",
		dexNo: 9,
		level: 77,
		gender: "male",
		type1: "Water",
		type2: "",
		moves: ["Rain Dance", "Blizzard", "Surf", "Whirlpool"],
	},
];

export const types = [
	"Normal",
	"Fire",
	"Fighting",
	"Water",
	"Flying",
	"Grass",
	"Poison",
	"Electric",
	"Ground",
	"Psychic",
	"Rock",
	"Ice",
	"Bug",
	"Dragon",
	"Ghost",
	"Dark",
	"Steel",
	"Fairy",
];
